#!/bin/bash

sudo rm -rf lib/SFML2.0/CMakeCache.txt
sudo rm -rf lib/SFML2.0/CMakeFiles/*
sudo rm -rf lib/SFML2.0/Makefile
sudo rm -rf lib/SFML2.0/cmake_install.cmake
sudo rm -rf lib/SFML2.0/install_manifest.txt
sudo rm -rf lib/SFML2.0/lib/*
sudo rm -rf lib/SFML2.0/src/SFML/Audio/CMakeFiles/*
sudo rm -rf lib/SFML2.0/src/SFML/Audio/Makefile
sudo rm -rf lib/SFML2.0/src/SFML/Audio/cmake_install.cmake
sudo rm -rf lib/SFML2.0/src/SFML/CMakeFiles/*
sudo rm -rf lib/SFML2.0/src/SFML/Graphics/CMakeFiles/*
sudo rm -rf lib/SFML2.0/src/SFML/Graphics/Makefile
sudo rm -rf lib/SFML2.0/src/SFML/Graphics/cmake_install.cmake
sudo rm -rf lib/SFML2.0/src/SFML/Makefile
sudo rm -rf lib/SFML2.0/src/SFML/Network/CMakeFiles/*
sudo rm -rf lib/SFML2.0/src/SFML/Network/Makefile
sudo rm -rf lib/SFML2.0/src/SFML/Network/cmake_install.cmake
sudo rm -rf lib/SFML2.0/src/SFML/System/CMakeFiles/*
sudo rm -rf lib/SFML2.0/src/SFML/System/Makefile
sudo rm -rf lib/SFML2.0/src/SFML/System/cmake_install.cmake
sudo rm -rf lib/SFML2.0/src/SFML/Window/CMakeFiles/*
sudo rm -rf lib/SFML2.0/src/SFML/Window/Makefile
sudo rm -rf lib/SFML2.0/src/SFML/Window/cmake_install.cmake
sudo rm -rf lib/SFML2.0/src/SFML/cmake_install.cmake
sudo rm -rf lib/SFML2.0/tools/pkg-config/sfml-all.pc
sudo rm -rf lib/SFML2.0/tools/pkg-config/sfml-audio.pc
sudo rm -rf lib/SFML2.0/tools/pkg-config/sfml-graphics.pc
sudo rm -rf lib/SFML2.0/tools/pkg-config/sfml-network.pc
sudo rm -rf lib/SFML2.0/tools/pkg-config/sfml-system.pc
sudo rm -rf lib/SFML2.0/tools/pkg-config/sfml-window.pc
