#ifndef DEFINE_AND_FUNCTION_HEADER
#define DEFINE_AND_FUNCTION_HEADER

/*!
 * \file GameEngineManager.hpp
 * \brief Classe de gestion du moteur de jeu
 * \author Simon Rousseau
 */

#define VITESSEPARDEFAUT 60
#define VITESSEMIN 100
#define VITESSEMAX 20
#define PASVITESSE 20
#define NOMBREBOMBEDEFAUT 2
#define RANGEDEFAUT 1
#define RANGEMIN 1
#define RANGEMAX 19
#define PASRANGE 1
#define ORIENTATIONDEFAUT ORIENTATION_RIGHT
#define BOMBTIMESTAMP 3
#define NOMBREBOX 0
#define DUREEFLAMME 1

#define LARGEUR 35
#define DISTANCEMINBETWEENTWOPLAYERS 2
#define TEMPSENTREDEUXACTIONSINFECTION 1

#endif
